pybuildtool:
  options:
    pylint_config_file: etc/pylint.rc
    pylint_work_dir: "./"

  pylint:
    raw_file_in: "{_1}/*.py"
    raw_depend_in: etc/pylint.rc

  addons:
    pylint:
      raw_file_in: "{_1}/{_2}/*.py"
      raw_depend_in: etc/pylint.rc

  core:
    pylint:
      raw_file_in: "{_1}/{_2}/*.py"
      raw_depend_in: etc/pylint.rc

  misc:
    pylint:
      raw_file_in: "{_1}/{_2}/*.py"
      raw_depend_in: etc/pylint.rc

  tests:
    pylint:
      raw_file_in: "{_1}/{_2}/*.py"
      raw_depend_in: etc/pylint.rc

  tools:
    pylint:
      raw_file_in: "{_1}/{_2}/*.py"
      raw_depend_in: etc/pylint.rc

  unittest:
    shell:
      options:
        _noop_retcodes_: [5]
        command: ./run pybin coverage run --include=./* -m py.test
      rule_in:
        - "{_1}/pylint"
        - "{_1}/addons/pylint"
        - "{_1}/core/pylint"
        - "{_1}/misc/pylint"
        - "{_1}/tests/pylint"
        - "{_1}/tools/pylint"
      raw_depend_in: build.yml

  coverage:
    shell:
      options:
        _noop_retcodes_: [1]
        command: ./run pybin coverage report -m --skip-covered
      rule_in:
        - "{_1}/unittest/shell"
